#ifndef _ADC_DRIVER_H_
#define _ADC_DRIVER_H_

#include <Include.h>
#define BRD_ADC_PREPARED_CHANNEL		(ADC_CHANNEL_4)
#define BRD_ADC_PREPARED_INTR			(ADC_ADINTEN4)

#define BRD_ADC_PREPARED_CH_PORT		(1)
#define BRD_ADC_PREPARED_CH_PIN			(30)
#define BRD_ADC_PREPARED_CH_FUNC_NO		(1)


#endif
