/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.12                          *
*        Compiled Jun 29 2011, 15:28:47                              *
*        (c) 2011 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x11)

WM_HWIN InPut_ThWin;
static void DialogBox_cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int Id,NCode;
  // USER START (Optionally insert additional variables)
//  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Listview'
    //
		hItem = pMsg->hWin;

		FRAMEWIN_AddCloseButton(pMsg->hWin, FRAMEWIN_BUTTON_RIGHT, 0);
		FRAMEWIN_SetFont(pMsg->hWin, &SIFA_Font);
		FRAMEWIN_SetTextColor(pMsg->hWin, 0x00000000);
		FRAMEWIN_SetTitleHeight(pMsg->hWin, 19);
		FRAMEWIN_SetFont(pMsg->hWin, &SIFA_Font);
		hItem = WM_GetDialogItem(pMsg->hWin,GUI_ID_BUTTON0);
		BUTTON_SetText(hItem,"取消");
		BUTTON_SetFont(hItem, &SIFA_Font);
		BUTTON_SetText(WM_GetDialogItem(pMsg->hWin,GUI_ID_BUTTON1),"确定");
		BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin,GUI_ID_BUTTON1), &SIFA_Font);
		BUTTON_SetText(WM_GetDialogItem(pMsg->hWin,GUI_ID_BUTTON2),"确定");
		BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin,GUI_ID_BUTTON2), &SIFA_Font);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
		if(NCode==WM_NOTIFICATION_RELEASED)
		{
			if(Id>='0'&Id<='9')EDIT_AddKey(InPut_ThWin,Id);
			if(Id=='.')EDIT_AddKey(InPut_ThWin,Id);
			if(Id=='-')EDIT_AddKey(InPut_ThWin,Id);
			if(Id=='+')EDIT_AddKey(InPut_ThWin,Id);
		}
    switch(Id) {
			case GUI_ID_BUTTON0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				 GUI_EndDialog(pMsg->hWin,0);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			case GUI_ID_BUTTON1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,1);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			case GUI_ID_BUTTON2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				  GUI_EndDialog(pMsg->hWin,1);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			case '<': // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				 EDIT_AddKey(InPut_ThWin,GUI_KEY_BACKSPACE);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			case 20: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
					if(BUTTON_GetBkColor(WM_GetDialogItem(pMsg->hWin,20),0)==GUI_WHITE)
						BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin,20),0,BUTTON_GetBkColor(WM_GetDialogItem(pMsg->hWin,'A'),0)); 
					else BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin,20),0,GUI_WHITE);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
				
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
uint8 MY_MessageBoxYesNo(const char *Msg,const char *Title,uint8 flag) {
  WM_HWIN hWin,hItem;
	uint8 r;
	static const GUI_WIDGET_CREATE_INFO _aDialog[] = {
	{ FRAMEWIN_CreateIndirect, "", ID_FRAMEWIN_0, 0, 0, 480/3, 272/3, 0, 100, 0 },
	{ TEXT_CreateIndirect, "", GUI_ID_TEXT0, 4, 6, 120, 16, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "", GUI_ID_BUTTON0, 5, 30, 50, 30, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "", GUI_ID_BUTTON1, 100, 30, 50, 30, 0, 0, 0 },
};
  hWin = GUI_CreateDialogBox(_aDialog, GUI_COUNTOF(_aDialog), &DialogBox_cbDialog, WM_HBKWIN, 480/3, 272/3);
	FRAMEWIN_SetText(hWin, Title);
	hItem = WM_GetDialogItem(hWin,GUI_ID_TEXT0);
	TEXT_SetText(hItem,Msg);
	TEXT_SetFont(hItem, &SIFA_Font);
	r= GUI_ExecCreatedDialog(hWin);
	DeBug("return=%d",r,Infor_Infor);
  return r;
}
uint8 MY_MessageBoxYes(const char *Msg,const char *Title,uint8 flag) {
  WM_HWIN hWin,hItem;
	uint8 r;
	static const GUI_WIDGET_CREATE_INFO _aDialog[] = {
	{ FRAMEWIN_CreateIndirect, "", ID_FRAMEWIN_0, 0, 0, 480/3, 272/3, 0, 100, 0 },
	{ TEXT_CreateIndirect, "", GUI_ID_TEXT0, 4, 6, 120, 16, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "", GUI_ID_BUTTON1, 50, 30, 55, 30, 0, 0, 0 },
	};
	hWin = GUI_CreateDialogBox(_aDialog, GUI_COUNTOF(_aDialog), &DialogBox_cbDialog, WM_HBKWIN, 480/3, 272/3);
	FRAMEWIN_SetText(hWin, Title);
	hItem = WM_GetDialogItem(hWin,GUI_ID_TEXT0);
	TEXT_SetText(hItem,Msg);
	TEXT_SetFont(hItem, &SIFA_Font);
	r= GUI_ExecCreatedDialog(hWin);
	return r;
}
char *MY_GetNumber(WM_HWIN ThWin,const char *Title,uint8 flag){
	const uint8 SX=0,SY=0,X=50,Y=50;
	WM_HWIN hWin;
	static const GUI_WIDGET_CREATE_INFO _aDialog[] = {
	{ FRAMEWIN_CreateIndirect, "", ID_FRAMEWIN_0, 0, 2, X*4+6, Y*4+27, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "1", '1', SX+X*0, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "2", '2', SX+X*1, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "3", '3', SX+X*2, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "4", '4', SX+X*3, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "5", '5', SX+X*0, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "6", '6', SX+X*1, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "7", '7', SX+X*2, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "8", '8', SX+X*3, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "9", '9', SX+X*0, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "0", '0', SX+X*1, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, ".", '.', SX+X*2, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "<<", '<',SX+X*3, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "-", '-', SX+X*0, SY+Y*3, X, Y, 6, 6, 6 },
	{ BUTTON_CreateIndirect, "+", '+', SX+X*1, SY+Y*3, X, Y, 6, 6, 6 },
	{ BUTTON_CreateIndirect, "EN", 128, SX+X*2, SY+Y*3, X, Y, 6, 6, 6 },
	{ BUTTON_CreateIndirect, "", GUI_ID_BUTTON2,SX+X*3, SY+Y*3, X, Y, 0, 0, 0 },
	
	};
	static const GUI_WIDGET_CREATE_INFO EN_aDialog[] = {
	{ FRAMEWIN_CreateIndirect, "", ID_FRAMEWIN_0, 0, 0, 480, 272, 0, 100, 0 },
	{ EDIT_CreateIndirect, "", GUI_ID_EDIT0, 0, 5, 475, 28, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "1", '1', SX+X*0, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "2", '2', SX+X*1, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "3", '3', SX+X*2, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "4", '4', SX+X*3, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "5", '5', SX+X*4, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "6", '6', SX+X*5, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "7", '7', SX+X*6, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "8", '8', SX+X*7, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "9", '9', SX+X*8, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "0", '0', SX+X*9, SY+Y*0, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "<<", '<',SX+X*10+8, SY+Y*0, X, Y, 0, 0, 0 },

	{ BUTTON_CreateIndirect, "Q", 'Q', SX+X*0, SY+Y*1, X, Y, 6, 6, 6 },
	{ BUTTON_CreateIndirect, "W", 'W', SX+X*1, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "E", 'E', SX+X*2, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "R", 'R', SX+X*3, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "T", 'T', SX+X*4, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "Y", 'Y', SX+X*5, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "U", 'U', SX+X*6, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "I", 'I', SX+X*7, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "O", 'O', SX+X*8, SY+Y*1, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "P", 'P', SX+X*9, SY+Y*1, X, Y, 0, 0, 0 },
	
//	{ BUTTON_CreateIndirect, "Caps", 20, SX+X*0  , SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "A", 'A', SX+X*0, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "S", 'S', SX+X*1, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "D", 'D', SX+X*2, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "F", 'F', SX+X*3, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "G", 'G', SX+X*4, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "H", 'H', SX+X*5, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "J", 'J', SX+X*6, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "K", 'K', SX+X*7, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "L", 'L', SX+X*8, SY+Y*2, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "", GUI_ID_BUTTON2,SX+X*9, SY+Y*2, X, Y, 0, 0, 0 },

	{ BUTTON_CreateIndirect, "SHIF", 16, SX+X*0 , SY+Y*3, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "Z", 'Z', SX+X*0+X*1, SY+Y*3, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "X", 'X', SX+X*1+X*1, SY+Y*3, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "C", 'C', SX+X*2+X*1, SY+Y*3, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "V", 'V', SX+X*3+X*1, SY+Y*3, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "B", 'B', SX+X*4+X*1, SY+Y*3, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "N", 'N', SX+X*5+X*1, SY+Y*3, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "M", 'M', SX+X*6+X*1, SY+Y*3, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, ",", ',', SX+X*7+X*1, SY+Y*3, X, Y, 0, 0, 0 },
	{ BUTTON_CreateIndirect, ".", '.', SX+X*8+X*1, SY+Y*3, X, Y, 0, 0, 0 },
	
	};
	if(InPut_ThWin!=0)
	{
		InPut_ThWin=ThWin;
		return 0;
	}
	InPut_ThWin=ThWin;
	hWin = GUI_CreateDialogBox(_aDialog, GUI_COUNTOF(_aDialog), &DialogBox_cbDialog, WM_HBKWIN, 120, 10);
	WM_SetStayOnTop(hWin,1);
	FRAMEWIN_SetText(hWin, Title);
	FRAMEWIN_SetMoveable(hWin, 1);
	GUI_ExecCreatedDialog(hWin);
	//hItem = WM_GetDialogItem(hWin, GUI_ID_EDIT0);
	//EDIT_GetText(hItem,Msg,20);
	//StringCoppy("测试字体",(void*)Msg);
	InPut_ThWin=0;
	return 0;
}
