/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.12                          *
*        Compiled Jun 29 2011, 15:28:47                              *
*        (c) 2011 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x11)
#define ID_LISTVIEW_0 (GUI_ID_USER + 0x12)
#define ID_BUTTON_0   (GUI_ID_USER + 0x23)
#define ID_BUTTON_1   (GUI_ID_USER + 0x14)
#define ID_BUTTON_2   (GUI_ID_USER + 0x15)
#define ID_BUTTON_3   (GUI_ID_USER + 0x16)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO History_aDialog[] = {
	{ FRAMEWIN_CreateIndirect, "历史记录", ID_FRAMEWIN_0, 0, 0, 480, 272, 0, 100, 0 },
	{ LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 0, 0, 410, 250, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "下页", ID_BUTTON_0, 415, 50, 50, 30, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "上页", ID_BUTTON_1, 415, 100, 50, 30, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "首页", ID_BUTTON_2, 415, 150, 50, 30, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "末页", ID_BUTTON_3, 415, 200, 50, 30, 0, 0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};
#include <songti16.c>
static const char * _aTable_1[][3] = {
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
  { "2016-05-05", "26.5", "90" },
};
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void History_cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
	HEADER_Handle listHeader;
  int Id,i,NCode;
  // USER START (Optionally insert additional variables)
//  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Listview'
    //
		hItem = pMsg->hWin;
    FRAMEWIN_SetTextColor(hItem, 0x00000000);
    FRAMEWIN_SetTitleHeight(hItem, 19);
    FRAMEWIN_SetFont(hItem, &SIFA_Font);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    LISTVIEW_AddColumn(hItem, 100, "记录时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 80, "温度(°)", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 100, "湿度(%)", GUI_TA_HCENTER | GUI_TA_VCENTER);
	  listHeader = LISTVIEW_GetHeader(hItem);
		WM_SetFocus(hItem);
		SCROLLBAR_CreateAttached(hItem, SCROLLBAR_CF_VERTICAL);
		SCROLLBAR_CreateAttached(hItem, WIDGET_STATE_FOCUSSABLE);
		HEADER_SetFont(listHeader,&SIFA_Font);
		LISTVIEW_SetFont(hItem,GUI_FONT_13_ASCII);
//		GUI_UC_SetEncodeUTF8();
    LISTVIEW_SetGridVis(hItem, 1);
	  for (i = 0; i < GUI_COUNTOF(_aTable_1); i++) {
    LISTVIEW_AddRow(hItem, _aTable_1[i]);
		}
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem, &SIFA_Font);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem, &SIFA_Font);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetFont(hItem, &SIFA_Font);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetFont(hItem, &SIFA_Font);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(History_aDialog, GUI_COUNTOF(History_aDialog), &History_cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
