/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.12                          *
*        Compiled Jun 29 2011, 15:28:47                              *
*        (c) 2011 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO Usart_aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 480, 272, 0, 100, 0 },
  { BUTTON_CreateIndirect, "Button", GUI_ID_BUTTON0, 385, 206, 74, 32, 0, 0, 0 },
  { MULTIEDIT_CreateIndirect, "", GUI_ID_MULTIEDIT0, 0, 0, 368, 205, 0, 0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", GUI_ID_DROPDOWN0, 385, 14, 74, 80, 0, 0, 0 },
  { EDIT_CreateIndirect, "Edit", GUI_ID_EDIT0, 0, 213, 368, 23, 0, 100, 0 },
  { BUTTON_CreateIndirect, "Button", GUI_ID_BUTTON1, 385, 106, 74, 32, 0, 0, 0 },
  { BUTTON_CreateIndirect, "Button", GUI_ID_BUTTON2, 385, 50, 74, 32, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void Usart_cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int Id, NCode;
	char Buf[20];
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
	
		FRAMEWIN_AddCloseButton(pMsg->hWin, FRAMEWIN_BUTTON_RIGHT, 0);
		FRAMEWIN_AddMinButton(pMsg->hWin, FRAMEWIN_BUTTON_RIGHT, 0);
		FRAMEWIN_SetText(hItem, "串口测试");
		FRAMEWIN_SetFont(pMsg->hWin, &SIFA_Font);
    FRAMEWIN_SetTitleHeight(hItem, 19);
    FRAMEWIN_SetTextColor(hItem, 0x00000000);
    //
    // Initialization of 'Button'
    //
    BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0), &SIFA_Font);
    BUTTON_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0), "发送");
    //
    // Initialization of 'Multiedit'
    //
		MULTIEDIT_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0),&SIFA_Font);
		MULTIEDIT_SetWrapWord(WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0));
    //
    // Initialization of 'Dropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_DROPDOWN0);
		DROPDOWN_SetFont(hItem,&SIFA_Font);
    DROPDOWN_AddString(hItem, "COM1");
    DROPDOWN_AddString(hItem, "COM2");
    DROPDOWN_AddString(hItem, "COM3");
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0);
    EDIT_SetText(hItem, "123");
    //
    // Initialization of 'Button'
    //
		BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON1), &SIFA_Font);
    BUTTON_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON1), "清除");
    BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON2), &SIFA_Font);
    BUTTON_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON2), "打开");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case GUI_ID_BUTTON0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0);
			EDIT_GetText(hItem, Buf,20);
			DeBug("%s",Buf,Infor_Infor);
			MULTIEDIT_AddText(WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0),"Send:");
			MULTIEDIT_AddText(WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0),Buf);
			MULTIEDIT_AddText(WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0),"\n");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case GUI_ID_MULTIEDIT0: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case GUI_ID_DROPDOWN0: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case GUI_ID_EDIT0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MY_GetNumber(WM_GetDialogItem(pMsg->hWin,GUI_ID_EDIT0),"输入",1);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case GUI_ID_BUTTON1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			EDIT_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0),"");
			MULTIEDIT_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0),"");
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case GUI_ID_BUTTON2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
void Usart_Task(void *Tags)
{
	WM_HWIN hWin;
	WM_HWIN hText;
	uint8 Length;
	uint8 Buf[20];
	hWin=(WM_HWIN)Tags;
	hText=WM_GetDialogItem(hWin, GUI_ID_MULTIEDIT0);
	DeBug("hWin=%d",hWin,Infor_Infor);
	while(1)
	{
		Length=USART_ReadDatas(UART_0,Buf,20,10);
		if(Length)
		{
			MULTIEDIT_AddText(hText,"Revice:");
			Buf[Length]=0;
			MULTIEDIT_AddText(hText,Buf);
		}
	}
}
WM_HWIN UsartFramewin(void);
WM_HWIN UsartFramewin(void) {
  WM_HWIN hWin;
	uint8 i;
  hWin = GUI_CreateDialogBox(Usart_aDialogCreate, GUI_COUNTOF(Usart_aDialogCreate), &Usart_cbDialog, WM_HBKWIN, 0, 0);
	Tos_TaskCreateFindID(Usart_Task,hWin,"Usart",2000);
	DeBug("hWin=%d",hWin,Infor_Infor);
	GUI_ExecCreatedDialog(hWin);
	i=Tos_GetTaskIDByName("Usart");
	Tos_TaskDelete(i);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
