/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.12                          *
*        Compiled Jun 29 2011, 15:28:47                              *
*        (c) 2011 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_RADIO_0 (GUI_ID_USER + 0x02)
#define ID_EDIT_1 (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
float test1;
static const GUI_WIDGET_CREATE_INFO _aDialogCreate3[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "保存", GUI_ID_BUTTON1, 480-105, 272-35, 50, 30, 0, 0, 0 },
  { BUTTON_CreateIndirect, "退出", GUI_ID_BUTTON0, 480-55, 272-35, 50, 30, 0, 0, 0 },
	{ EDIT_CreateIndirect, "", ID_EDIT_0, 0, 0, 100, 32, 0, 0, 0 },
	{ EDIT_CreateIndirect, "", ID_EDIT_1, 0, 32, 100, 32, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

static void _cbDialog3(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int Id, NCode;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
	
    // Initialization of 'EDIT'
	 hItem = pMsg->hWin;
	EDIT_SetFloatMode(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),test1,0,1000,4,GUI_EDIT_SIGNED);
	EDIT_SetTextAlign(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),GUI_TA_VCENTER);
	EDIT_SetFloatMode(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1),test1,-100,1000,2,GUI_EDIT_SIGNED);
	EDIT_SetTextAlign(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1),GUI_TA_VCENTER);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
			 case ID_EDIT_0: // Notifications sent by 'EDIT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			MY_GetNumber(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),"请输入数据",1);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			 case ID_EDIT_1: // Notifications sent by 'EDIT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			MY_GetNumber(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1),"请输入数据",1);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			case GUI_ID_BUTTON0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			test1=EDIT_GetFloatValue(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
				GUI_EndDialog(pMsg->hWin,1);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow1(void);
WM_HWIN CreateWindow1(void) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_aDialogCreate3, GUI_COUNTOF(_aDialogCreate3), &_cbDialog3, WM_HBKWIN, 0, 0);
	WM_SetFocus(hWin);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
