/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.12                          *
*        Compiled Jun 29 2011, 15:28:47                              *
*        (c) 2011 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include <anniu.c>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_RADIO_0 (GUI_ID_USER + 0x02)
#define ID_EDIT_1 (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate2[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "创建", GUI_ID_BUTTON0, 415, 30, 50, 30, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "记录", GUI_ID_BUTTON1, 415, 60, 50, 30, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "设置", GUI_ID_BUTTON2, 415, 90, 50, 30, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "管理", GUI_ID_BUTTON3, 415, 120, 50, 30, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "文件", GUI_ID_BUTTON4, 415, 150, 50, 30, 0, 0, 0 },
	{ BUTTON_CreateIndirect, "功能", GUI_ID_BUTTON5, 415, 180, 50, 30, 0, 0, 0 },
	{ TEXT_CreateIndirect, "60.2", GUI_ID_EDIT0, 0, 50, 200, 94, 0, 0, 0 },
	{ TEXT_CreateIndirect, "25.4°", GUI_ID_EDIT1, 0, 150, 300, 94, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

static void _cbDialog2(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int Id, NCode;

  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	hItem = pMsg->hWin;
	GUI_SetDefault();
	GUI_SetDefaultFont(&SIFA_Font);
	BUTTON_SetDefaultFont(&SIFA_Font);
	EDIT_SetDefaultFont(&SIFA_Font);
	EDIT_SetDefaultTextAlign(EDIT_CF_VCENTER);
	EDIT_SetTextAlign(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),EDIT_CF_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
	BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0), &SIFA_Font);
	BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON1), &SIFA_Font);
	BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON2), &SIFA_Font);
	BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON3), &SIFA_Font);
	BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON4), &SIFA_Font);
	BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON5), &SIFA_Font);
	TEXT_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0), GUI_FONT_D64);
	TEXT_SetTextColor(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0), GUI_GREEN);
	TEXT_SetFont(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT1), GUI_FONT_D60X80);
	TEXT_SetTextColor(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT1), GUI_BLUE);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	GUI_UC_SetEncodeUTF8();

    // USER END
    break;
	case WM_PAINT:
	
		break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'EDIT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			MY_GetNumber(WM_GetDialogItem(pMsg->hWin,ID_EDIT_0),"输入",1);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			case GUI_ID_BUTTON0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0);
				WM_DisableWindow(hItem);
				CreateMywindow();
				WM_EnableWindow(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			case GUI_ID_BUTTON1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem=CreateFramewin();
				FRAMEWIN_SetMoveable(hItem, 1);
				FRAMEWIN_AddCloseButton(hItem, FRAMEWIN_BUTTON_RIGHT, 0);
				FRAMEWIN_AddMaxButton(hItem, FRAMEWIN_BUTTON_RIGHT, 0);
				FRAMEWIN_AddMinButton(hItem, FRAMEWIN_BUTTON_RIGHT, 0);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			case GUI_ID_BUTTON2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        	hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON2);
					WM_DisableWindow(hItem);
					MY_MessageBoxYes("没有创建!","信息",0);
					WM_EnableWindow(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			case GUI_ID_BUTTON3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON3);
					WM_DisableWindow(hItem);
					if(MY_MessageBoxYesNo("是否继续?","信息",0))CreateWindow1();
					WM_EnableWindow(hItem);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
				case GUI_ID_BUTTON5: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					UsartFramewin();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
				case GUI_ID_BUTTON4: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					CreateFileBrower();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;
		uint8 *P_SIFA;
  hWin = GUI_CreateDialogBox(_aDialogCreate2, GUI_COUNTOF(_aDialogCreate2), &_cbDialog2, WM_HBKWIN, 0, 0);

	WM_SetFocus(hWin);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
